name: fitcrew
description: A new Flutter project.



publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'







dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  url_launcher: ^6.1.5


  
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:
  assets:
     - avatar.png
     - gmail.png
     - instagram.png
     - whatsapp.png
     - messenger.png
     - ytb.png

  
  
  


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
